<project name="congo-templates" default="jar">
    <target name="check-parser-uptodate">
        <uptodate property="parser.uptodate"
            targetfile="build/generated-java/org/congocc/templates/core/parser/CTLParser.java">
            <srcfiles dir="src/ccc" includes="*.ccc" />
        </uptodate>
    </target>

    <target name="congo-init">
        <available
           property="congo.jar.location"
           file="../congocc.jar"
           value="../congocc.jar"
        />
        <available
           property="congo.jar.location"
           file="../bin/congocc.jar"
           value="../bin/congocc.jar"
        />
        <available
           property="congo.jar.location"
           file="bootstrap/congocc.jar"
           value="bootstrap/congocc.jar"
        />
    </target>

    <target name="get-congo-jar" depends="congo-init" unless="congo.jar.location">
        <mkdir dir="bootstrap"/>
        <echo>Downloading congo jar...</echo>
        <get src="https://parsers.org/download/congocc.jar"
             dest="bootstrap/congocc.jar"
        />
        <property name="congo.jar.location"
                  value="bootstrap/congocc.jar"
        />
    </target>

    <target name="clean">
        <delete file="congo-templates.jar" />
        <delete dir="build" />
    </target>

    <target name="build-parser" depends="check-parser-uptodate,get-congo-jar" unless="parser.uptodate">
        <java fork="true" jar="${congo.jar.location}" failonerror="true">
            <assertions>
                <enable />
            </assertions>
            <arg line="-n -q -d build src/ccc/CTL.ccc" />
        </java>
    </target>

    <target name="compile" depends="build-parser">
        <mkdir dir="build/classes"/>
        <javac destdir="build/classes"
            deprecation="off"
            debug="on"
            optimize="off"
            failonerror="true"
            includeantruntime="false"
            release="17">
            <src path="src/java" />
            <src path="build/generated-java" />
        </javac>
    </target>

    <target name="jar" depends="compile">
        <copy file="LICENSE" todir="build/classes"/>
        <jar jarfile="congo-templates.jar"
            basedir="build/classes"
            compress="true"
            includes="org/congocc/templates/**/*.class,LICENSE">
            <manifest>
                <attribute name="Main-Class" value="org.congocc.templates.cli.CommandLine" />
            </manifest>
        </jar>
    </target>
</project>
